Repository MinuteMate/Seri-Android, pull requests merged in 2022-03, with the labels that each got.

#2 🔀 :: (#1) architecture
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hackaton/seriandroid/MainActivity.kt
  app/src/main/java/com/hackaton/seriandroid/data/.gitkeep
  app/src/main/java/com/hackaton/seriandroid/data/repository/auth/AuthApi.kt
  app/src/main/java/com/hackaton/seriandroid/di/SeriApplication.kt
  app/src/main/java/com/hackaton/seriandroid/di/module/DispatcherModule.kt
  app/src/main/java/com/hackaton/seriandroid/di/module/RetrofitModule.kt
  app/src/main/java/com/hackaton/seriandroid/ui/base/BaseActivity.kt
  app/src/main/java/com/hackaton/seriandroid/ui/base/BaseFragment.kt
  app/src/main/java/com/hackaton/seriandroid/ui/main/.gitkeep
  app/src/main/java/com/hackaton/seriandroid/ui/main/activity/MainActivity.kt
  app/src/main/java/com/hackaton/seriandroid/ui/splash/.gitkeep
  app/src/main/java/com/hackaton/seriandroid/ui/splash/activity/SplashActivity.kt
  app/src/main/java/com/hackaton/seriandroid/utils/EventFlow.kt
  app/src/main/java/com/hackaton/seriandroid/utils/Lifecycle.kt
  app/src/main/java/com/hackaton/seriandroid/utils/View.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/themes.xml
Labels: 기능 추가, 프로젝트 설정

#5 🔀 :: (#4) network setup
  app/src/main/java/com/hackaton/seriandroid/data/local/datasource/.gitkeep
  app/src/main/java/com/hackaton/seriandroid/data/local/storage/.gitkeep
  app/src/main/java/com/hackaton/seriandroid/data/remote/api/.gitkeep
  app/src/main/java/com/hackaton/seriandroid/data/remote/api/AuthApi.kt
  app/src/main/java/com/hackaton/seriandroid/data/remote/datasource/.gitkeep
  app/src/main/java/com/hackaton/seriandroid/data/remote/dto/request/.gitkeep
  app/src/main/java/com/hackaton/seriandroid/data/remote/dto/response/.gitkeep
  app/src/main/java/com/hackaton/seriandroid/data/remote/network/ErrorResponse.kt
  app/src/main/java/com/hackaton/seriandroid/data/remote/network/ResultWrapper.kt
  app/src/main/java/com/hackaton/seriandroid/data/remote/network/SafeApiRequest.kt
  app/src/main/java/com/hackaton/seriandroid/data/repository/.gitkeep
  app/src/main/java/com/hackaton/seriandroid/data/repository/auth/AuthApi.kt
  app/src/main/java/com/hackaton/seriandroid/di/module/RetrofitModule.kt
Labels: 프로젝트 설정

#9 🔀 :: (#8) auth storage
  app/build.gradle
  app/src/main/java/com/hackaton/seriandroid/data/local/datasource/LocalAuthDataSource.kt
  app/src/main/java/com/hackaton/seriandroid/data/local/datasource/LocalAuthDataSourceImpl.kt
  app/src/main/java/com/hackaton/seriandroid/data/local/storage/AuthDataStorage.kt
  app/src/main/java/com/hackaton/seriandroid/data/local/storage/AuthDataStorageImpl.kt
  app/src/main/java/com/hackaton/seriandroid/data/remote/datasource/RemoteAuthDataSource.kt
  app/src/main/java/com/hackaton/seriandroid/data/repository/AuthRepository.kt
Labels: 기능 추가

#10 🔀 :: (#7) auth design
  app/src/main/res/drawable/auth_login_btn_radius.xml
  app/src/main/res/drawable/auth_login_line.png
  app/src/main/res/layout/fragment_auth_login.xml
  app/src/main/res/layout/fragment_auth_login_main.xml
Labels: 기능 추가

#13 🔀 :: (#12) fix build error
  app/build.gradle
  app/src/main/java/com/hackaton/seriandroid/data/remote/datasource/RemoteAuthDataSourceImpl.kt
  app/src/main/java/com/hackaton/seriandroid/di/module/LocalDataSourceModule.kt
  app/src/main/java/com/hackaton/seriandroid/di/module/RemoteDataSourceModule.kt
  app/src/main/java/com/hackaton/seriandroid/di/module/StorageModule.kt
  app/src/main/java/com/hackaton/seriandroid/ui/main/activity/MainActivity.kt
  app/src/main/java/com/hackaton/seriandroid/ui/splash/activity/SplashActivity.kt
Labels: 버그

#14 🔀 :: (#14) implementation
  app/build.gradle
Labels: 기능 추가

#15 🔀 :: (#7) auth design
  app/build.gradle
  app/src/main/res/drawable/auth_email_otp_background.xml
  app/src/main/res/drawable/auth_right_img.png
  app/src/main/res/layout/activity_auth_main.xml
  app/src/main/res/layout/fragemnt_auth_password_re.xml
  app/src/main/res/layout/fragment_auth_email_code.xml
  app/src/main/res/layout/fragment_auth_email_input.xml
  app/src/main/res/layout/fragment_auth_finish.xml
  app/src/main/res/layout/fragment_auth_name_input.xml
  app/src/main/res/layout/fragment_auth_password.xml
Labels: 기능 추가, 프로젝트 설정

#17 🔀 :: (#16) auth retrofit interface
  app/src/main/java/com/hackaton/seriandroid/data/remote/api/AuthApi.kt
  app/src/main/java/com/hackaton/seriandroid/data/remote/dto/request/SignInRequest.kt
  app/src/main/java/com/hackaton/seriandroid/data/remote/dto/request/SignUpRequest.kt
  app/src/main/java/com/hackaton/seriandroid/data/remote/dto/response/FetchVerifyCodeResponse.kt
  app/src/main/java/com/hackaton/seriandroid/data/remote/dto/response/SignUpResponse.kt
Labels: 기능 추가

#22 🔀 :: (#19) auth design update
  app/src/main/res/drawable/auith_profile_plus_img.png
  app/src/main/res/drawable/auth_profile_circle.xml
  app/src/main/res/layout/fragment_auth_set_profile.xml
Labels: 기능 추가

#24 🔀 :: (#3) design default setup
  app/src/main/res/drawable/auith_profile_plus_img.png
  app/src/main/res/drawable/auth_login_line.png
  app/src/main/res/drawable/auth_login_line.xml
  app/src/main/res/drawable/auth_profile_circle.xml
  app/src/main/res/drawable/auth_profile_plus_img.xml
  app/src/main/res/drawable/auth_right_img.png
  app/src/main/res/drawable/auth_right_img.xml
  app/src/main/res/font/noto_sans_kr_black.ttf
  app/src/main/res/font/noto_sans_kr_bold.ttf
  app/src/main/res/font/noto_sans_kr_light.ttf
  app/src/main/res/font/noto_sans_kr_medium.ttf
  app/src/main/res/font/noto_sans_kr_regular.ttf
  app/src/main/res/font/noto_sans_kr_thin.ttf
  app/src/main/res/layout/fragment_auth_set_profile.xml
  app/src/main/res/values/colors.xml
Labels: 프로젝트 설정

#25 🔀 :: (#18) auth repository
  app/src/main/java/com/hackaton/seriandroid/data/remote/api/AuthApi.kt
  app/src/main/java/com/hackaton/seriandroid/data/remote/datasource/RemoteAuthDataSource.kt
  app/src/main/java/com/hackaton/seriandroid/data/remote/datasource/RemoteAuthDataSourceImpl.kt
  app/src/main/java/com/hackaton/seriandroid/data/remote/dto/response/ReissueTokenResponse.kt
  app/src/main/java/com/hackaton/seriandroid/data/remote/dto/response/SignInResponse.kt
  app/src/main/java/com/hackaton/seriandroid/data/repository/AuthRepository.kt
  app/src/main/java/com/hackaton/seriandroid/di/module/RetrofitModule.kt
Labels: 기능 추가

#30 🔀 :: (#27) auth design add
  app/src/main/java/com/hackaton/seriandroid/ui/auth/AuthViewModel.kt
  app/src/main/java/com/hackaton/seriandroid/ui/auth/mail/AuthEmailCodeFragment.kt
  app/src/main/res/drawable/auth_login_btn_radius.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_auth_email_code.xml
  app/src/main/res/layout/fragment_auth_email_input.xml
  app/src/main/res/layout/fragment_auth_finish.xml
  app/src/main/res/layout/fragment_auth_login.xml
  app/src/main/res/layout/fragment_auth_name_input.xml
  app/src/main/res/layout/fragment_auth_password.xml
  app/src/main/res/layout/fragment_auth_password_re.xml
Labels: 기능 추가

#29 🔀 :: (#28) game design
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hackaton/seriandroid/ui/game/.gitkeep
  app/src/main/java/com/hackaton/seriandroid/ui/game/activity/GameActivity.kt
  app/src/main/java/com/hackaton/seriandroid/ui/game/model/GameMessage.kt
  app/src/main/res/drawable/bg_chat_page.png
  app/src/main/res/drawable/bg_et_chat.xml
  app/src/main/res/drawable/chat_mine_view.xml
  app/src/main/res/drawable/chat_partner_view.xml
  app/src/main/res/drawable/ic_send.xml
  app/src/main/res/drawable/progressbar_horizontal.xml
  app/src/main/res/font/neodgm_pro.ttf
  app/src/main/res/layout/activity_game.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: 기능 추가

#32 🔀 :: (#31) main ui
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hackaton/seriandroid/ui/auth/profile/AuthSetProfileFragment.kt
  app/src/main/java/com/hackaton/seriandroid/ui/main/MainActivity.kt
  app/src/main/res/drawable/bg_main.png
  app/src/main/res/drawable/ic_help.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/layout/activity_auth_main.xml
  app/src/main/res/layout/activity_main.xml
  build.gradle
Labels: 기능 추가

#33 🔀 :: (#31) main ui (splash)
  app/src/main/java/com/hackaton/seriandroid/ui/splash/activity/SplashActivity.kt
  app/src/main/res/drawable/bg_splash.png
  app/src/main/res/drawable/bg_splash_login.xml
  app/src/main/res/drawable/bg_splash_register.xml
  app/src/main/res/layout/activity_splash.xml
Labels: 기능 추가

#35 🔀 :: (#34) splash bug
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hackaton/seriandroid/ui/auth/finish/AuthFinishFragment.kt
  app/src/main/java/com/hackaton/seriandroid/ui/auth/login/LoginActivity.kt
  app/src/main/java/com/hackaton/seriandroid/ui/splash/activity/SplashActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_auth_login.xml
Labels: 버그

#44 🔀 :: game design update
  app/src/main/java/com/hackaton/seriandroid/ui/game/model/GameEnterMessage.kt
  app/src/main/java/com/hackaton/seriandroid/ui/game/model/GameMeMessage.kt
  app/src/main/res/drawable/content_start.png
  app/src/main/res/drawable/grouop_1518.png
  app/src/main/res/drawable/group1515.png
  app/src/main/res/drawable/group1522.png
  app/src/main/res/drawable/group_1496.png
  app/src/main/res/drawable/group_1517.png
  app/src/main/res/drawable/group_1519.png
  app/src/main/res/drawable/group_1520.png
  app/src/main/res/drawable/group_1521.png
  app/src/main/res/drawable/group_1523.png
  app/src/main/res/drawable/group_1524.png
  app/src/main/res/drawable/group_1525.png
  app/src/main/res/drawable/group_1526.png
  app/src/main/res/drawable/group_1528.png
  app/src/main/res/drawable/group_1529.png
  app/src/main/res/drawable/group_1531.png
  app/src/main/res/drawable/group_1532.png
  app/src/main/res/drawable/group_1533.png
  app/src/main/res/drawable/group_1534.png
  app/src/main/res/drawable/group_1535.png
  app/src/main/res/drawable/group_1536.png
  app/src/main/res/drawable/group_1537.png
  app/src/main/res/drawable/group_1538.png
  app/src/main/res/drawable/group_1540.png
  app/src/main/res/drawable/group_1542.png
  app/src/main/res/drawable/group_1543.png
  app/src/main/res/drawable/group_1546.png
  app/src/main/res/drawable/group_1547.png
  app/src/main/res/drawable/group_1550.png
  app/src/main/res/drawable/group_21.png
  app/src/main/res/drawable/group_22.png
  app/src/main/res/drawable/group_82.png
  app/src/main/res/drawable/group_93.png
  app/src/main/res/drawable/grup_1527.png
  app/src/main/res/drawable/ra_65.png
  app/src/main/res/drawable/topic.png
  app/src/main/res/layout/activity_game.xml
  app/src/main/res/layout/game_enter_list.xml
  app/src/main/res/layout/game_other_list.xml
  app/src/main/res/layout/gmae_me_list.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가
